version: '3.8'

services:
  api:
    build: .
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ./model_assets:/app/model_assets
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: .
    command: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./model_assets:/app/model_assets
    env_file:
      - .env
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000